set_property SRC_FILE_INFO {cfile:c:/Users/yuqiwen3/lab7/lab7.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0.xdc rfile:../../../../../lab7.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0.xdc id:1 order:EARLY scoped_inst:inst/clk_wiz/inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/yuqiwen3/lab7/lab7.runs/mb_block_hdmi_text_controller_0_0_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name axi_aclk [get_ports axi_aclk]
current_instance inst/clk_wiz/inst
set_property src_info {type:SCOPED_XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PHASESHIFT_MODE WAVEFORM [get_cells mmcm_adv_inst]
current_instance
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clkfbout_clk_wiz_0 -source [get_pins inst/clk_wiz/inst/mmcm_adv_inst/CLKIN1] -multiply_by 1 -add -master_clock [get_clocks axi_aclk] [get_pins inst/clk_wiz/inst/mmcm_adv_inst/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_out1_clk_wiz_0 -source [get_pins inst/clk_wiz/inst/mmcm_adv_inst/CLKIN1] -edges {1 2 3} -edge_shift {0.000 15.000 30.000} -add -master_clock [get_clocks axi_aclk] [get_pins inst/clk_wiz/inst/mmcm_adv_inst/CLKOUT0]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_out2_clk_wiz_0 -source [get_pins inst/clk_wiz/inst/mmcm_adv_inst/CLKIN1] -edges {1 2 3} -edge_shift {0.000 -1.000 -2.000} -add -master_clock [get_clocks axi_aclk] [get_pins inst/clk_wiz/inst/mmcm_adv_inst/CLKOUT1]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/clk_wiz/inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/clk_wiz]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/vga_to_hdmi]
